#
# Makefile for the Linux kernel toshiba drivers.
#
#

obj-y += model/
obj-y += mfd/
obj-y += subpmic/
obj-y += keypad/
obj-y += touchscreen/
obj-y += irremo/
obj-y += memread/
obj-y += sd/
obj-y += pipe/
obj-y += fcsmd/
obj-y += input/
obj-y += fcfd/
